### ISSUE TITLE
No icon for simple-client in RHEL 9

### ISSUE THREAD

**Issue by eboudrand** [3v1n0/indicators-examples-snaps#1]
Hi,

I cannot get an icon for simple-client when I am using Red Hat Entreprise Linux 9. 

I downloaded code and compiled simple-client in gtk3-appindicator directory. When I run it, I have message :

`(simple-client:7017): Gtk-CRITICAL **: 12:58:20.650: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)`

I can debug it with `G_DEBUG=fatal-criticals gdb simple-client -d  .`

For getting details for backtrace, I had to install these packages : 

```
dnf debuginfo-install gtk3-3.24.31-2.el9.x86_64
dnf debuginfo-install libindicator-gtk3-12.10.1-22.el9.x86_64
dnf debuginfo-install libappindicator-gtk3
```

Backtrace is then : 

```
(gdb) bt
#0  0x00007ffff70ae5a7 in g_logv () at /lib64/libglib-2.0.so.0
#1  0x00007ffff70ae863 in g_log () at /lib64/libglib-2.0.so.0
#2  0x00007ffff79770c1 in gtk_widget_get_scale_factor (widget=<optimized out>) at ../gtk/gtkwidget.c:10972
#3  0x00007ffff7a487a1 in gtk_status_icon_update_image.isra.0 (status_icon=<optimized out>, status_icon=<optimized out>) at ../gtk/deprecated/gtkstatusicon.c:1409
#4  0x00007ffff7fa8de0 in status_icon_changes (self=<optimized out>, data=<optimized out>) at ../../src/app-indicator.c:1648
#5  0x00007ffff7fa8fee in fallback (self=0x70f920) at ../../src/app-indicator.c:1538
#6  0x00007ffff7fa6815 in fallback_timer_expire (data=0x70f920) at ../../src/app-indicator.c:1474
#7  0x00007ffff70a9681 in g_timeout_dispatch () at /lib64/libglib-2.0.so.0
#8  0x00007ffff70a8e2f in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#9  0x00007ffff70fd508 in g_main_context_iterate.constprop () at /lib64/libglib-2.0.so.0
#10 0x00007ffff70a8483 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#11 0x0000000000402780 in main (argc=<optimized out>, argv=<optimized out>) at simple-client.c:276
```

**Comment by eboudrand** [comment]
It was simply a configuration issue
